import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { MainLayout } from "~/layouts";
import { ThemeProvider } from "~/components/ui/theme-provider";
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: "Hightool v2",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={` ${inter.className} antialiased`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <MainLayout>
                        <div className='absolute my-20 transition-all duration-1000'>
                            {children}
                        </div>
                    </MainLayout>
                </ThemeProvider>
            </body>
        </html>
    );
}
