import { Inter } from 'next/font/google';
import 'tailwindcss/tailwind.css';
import Header from '~/components/layout';
import Footer from '~/components/layout/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <div className='lg:pt-20 md:pt-24 pt-28 bg-[url("https://flowbite.s3.amazonaws.com/docs/jumbotron/hero-pattern.svg")]'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
