import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { MainLayout } from "~/layouts";
import { ThemeProvider } from "~/components/ui/theme-provider";
import { ManiFooter } from "~/components";
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: "Hightool v2",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
    return (
        <html lang="en">
            <head />
            <body className={`${inter.className} antialiased`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <MainLayout>
                        {children}
                    </MainLayout>
                </ThemeProvider>
                <ManiFooter />
            </body>
        </html>
    );
}
