
export default function Home() {
    return (
        <div className="flex flex-wrap">
            <main className="flex flex-wrap">
            The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.
            The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.
            The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.The tag generator provides you with effective tags based on your title and helps your content to be more recommended on your platform beyond your followers.
            </main>
        </div>
    );
}
